/* Agregar registros de MONEDA */
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(1, 'AED', 'Dírham de los Emiratos Árabes Unidos');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(2, 'AFN', 'Afgani');
INSERT INTO Moneda (Id, Sigla, Moneda)  VALUES(3, 'ALL', 'Lek');
...
...(seguirán todos los INSERT, más de 170)...
...

/* Agregar registros de PAIS */
INSERT INTO Pais(Id, Pais, CodigoAlfa2, CodigoAlfa3, IdMoneda) VALUES  (004, 'Afganistán', 'AF', 'AFG',2);
INSERT INTO Pais(Id, Pais, CodigoAlfa2, CodigoAlfa3, IdMoneda) VALUES  (248, 'Åland', 'AX', 'ALA',49);
INSERT INTO Pais(Id, Pais, CodigoAlfa2, CodigoAlfa3, IdMoneda) VALUES  (008, 'Albania', 'AL', 'ALB',3);
...
...(seguirán todos los países, más de 200)...
...

